/**
 * Copyright: ThoughtSpot Inc. 2015
 * Author: Rahul Paliwal (rahul@thoughtspot.com)
 *
 * @fileoverview The UserAction class.
 *
 */

'use strict';

blink.app.factory('UserAction', [function() {
    var userActionTypeEnum = {
        ADD_VIZ_TO_PINBOARD: 'add-viz-to-pinboard',
        DELETE_VIZ_FROM_PINBOARD: 'delete-viz-from-pinboard',
        CREATE_PINBOARD: 'create-pinboard',
        CREATE_LABEL: 'create-label',
        DELETE_LABELS: 'delete-labels',
        DELETE_METADATA_ITEMS: 'delete-metadata-items',
        DELETE_PINBOARDS: 'delete-pinboards',
        DELETE_ANSWERS: 'delete-answers',
        DELETE_TABLES: 'delete-tables',
        CREATE_RELATED_LINK: 'create-related-link',
        UPDATE_RELATED_LINK: 'update-related-link',
        DELETE_RELATED_LINK: 'delete-related-link',
        CREATE_RELATIONSHIP: 'create-relationship',
        FETCH_RELATED_LINK_DETAILS: 'fetch-related-link-details',
        UPDATE_RELATIONSHIP: 'update-relationship',
        DELETE_RELATIONSHIP: 'delete-relationship',
        FETCH_TABLE_DETAILS: 'fetch-table-details',
        FETCH_TABLES_DETAILS: 'fetch-tables-details',
        FETCH_DATA_SOURCES_DETAILS: 'fetch-data-sources-details',
        FETCH_DATA_SOURCE_DETAILS: 'fetch-data-source-details',
        FETCH_METADATA_DETAILS: 'fetch-metadata-details',
        FETCH_ANSWER_DETAILS: 'fetch-answer-details',
        FETCH_PINBOARD_DETAILS: 'fetch-pinboard-details',
        FETCH_WORKSHEET_DETAILS: 'fetch-worksheet-details',
        SAVE_TABLE_MODEL: 'save-table-model',
        SAVE_VIZ_CONTEXT: 'save-viz-context',
        SAVE_ANSWER_MODEL: 'save-answer-model',
        SAVE_PINBOARD_MODEL: 'save-pinboard-model',
        SAVE_WORKSHEET_MODEL: 'save-worksheet-model',
        SAVE_AS_ANSWER_MODEL: 'save-as-answer-model',
        SAVE_AS_PINBOARD_MODEL: 'save-as-pinboard-model',
        SAVE_AS_WORKSHEET_MODEL: 'save-as-worksheet-model',
        SAVE_TAG: 'save-tag',
        ASSIGN_TAG: 'assign-tag',
        UNASSIGN_TAG: 'unassign-tag',
        EXPORT_OBJECTS: 'export-objects',
        IMPORT_OBJECTS: 'import-objects',
        FETCH_METADATA_LIST: 'fetch-metadata-list',
        FETCH_TABLE_LIST: 'fetch-table-list',
        FETCH_RELATIONSHIP_LIST: 'fetch-relationship-list',
        FETCH_ANSWER_LIST: 'fetch-answer-list',
        FETCH_PINBOARD_LIST: 'fetch-pinboard-list',
        FETCH_WORKSHEET_LIST: 'fetch-worksheet-list',
        FETCH_AGGR_WORKSHEET_LIST: 'fetch-aggr-worksheet-list',
        FETCH_IMPORTED_DATA_LIST: 'fetch-imported-data-list',
        FETCH_SYSTEM_TABLE_LIST: 'fetch-system-table-list',
        FETCH_DB_VIEW_LIST: 'fetch-db-view-list',
        FETCH_DATA_SOURCE_LIST: 'fetch-data-source-list',
        FETCH_COLUMN_LIST: 'fetch-column-list',
        FETCH_TAG_LIST: 'fetch-tag-list',
        FETCH_ANSWER: 'fetch-answer',
        FETCH_WORKSHEET: 'fetch-worksheet',
        FETCH_LEAF_LEVEL_DATA: 'fetch-leaf-level-data',
        FETCH_EXCEL_DATA: 'fetch-excel-data',
        FETCH_PINBOARD_AS_PDF: 'fetch-pinboard-as-pdf',
        FETCH_VIZ_DATA: 'fetch-viz-data',
        FETCH_VIZS_DATA: 'fetch-vizs-data',
        FETCH_CHART_DATA: 'fetch-chart-data',
        FETCH_TABLE_DATA: 'fetch-table-data',
        FETCH_WORKSHEET_DATA: 'fetch-worksheet-data',
        FETCH_FILTER_DATA: 'fetch-filter-data',
        UPDATE_HEADLINE_DATA: 'update-headline-data',
        FETCH_NATURAL_QUERY: 'fetch-natural-query',
        CREATE_AGGR_WORKSHEET: 'create-aggr-worksheet',
        UPDATE_AGGR_WORKSHEET: 'update-aggr-worksheet',
        FETCH_TABLE_DEPENDENTS: 'fetch-table-dependents',
        FETCH_COLUMN_DEPENDENTS: 'fetch-column-dependents',
        FETCH_INCOMPLETE_LIST: 'fetch-incomplete-list',
        UPDATE_FORMULA: 'update-formula',
        FETCH_MEM_CACHE_STATS: 'fetch-mem-cache-stats',
        CLEAR_MEM_CACHE: 'clear-mem-cache',
        SEARCH_MEM_CACHE: 'search-mem-cache',
        FETCH_LOGGERS: 'fetch-loggers',
        SET_LOG_LEVEL: 'set-log-level',
        GET_DEBUG_INFO: 'get-debug-info',
        FETCH_TABLE_PERMISSIONS: 'fetch-table-permissions',
        FETCH_ANSWER_PERMISSIONS: 'fetch-answer-permissions',
        FETCH_PINBOARD_PERMISSIONS: 'fetch-pinboard-permissions',
        FETCH_METADATA_PERMISSIONS: 'fetch-metadata-permissions',
        CACHE_DATA: 'cache-data',
        READ_COLUMNS: 'read-columns',
        READ_KEYS: 'read-keys',
        READ_RELATIONSHIPS: 'read-relationships',
        LOAD_DATA: 'load-data',
        CREATE_TABLE: 'create-table',
        FETCH_DATA_ROWS: 'fetch-data-rows',
        DELETE_FILES: 'delete-files',
        ABORT_CREATE_TABLE: 'abort-create-table',
        FETCH_SCHEMA: 'fetch-schema',
        FETCH_TABLE_MODELS: 'fetch-table-models',
        FETCH_SAMPLE_VALUES: 'fetch-sample-values',
        PARSE_SQL: 'parse-sql',
        EXECUTE_SQL: 'execute-sql',
        FETCH_USERS_LIST: 'fetch-users-list',
        FETCH_GROUPS_LIST: 'fetch-groups-list',
        FETCH_JOB_LIST: 'fetch-jobs-list',
        FETCH_ROLES_LIST: 'fetch-roles-list',
        FETCH_USERS_AND_GROUPS_LIST: 'fetch-users-and-groups-list',
        CREATE_USER: 'create-user',
        CREATE_JOB: 'create-job',
        CREATE_GROUP: 'create-group',
        CREATE_ROLE: 'create-role',
        UPDATE_USER: 'update-user',
        UPDATE_JOB: 'update-job',
        UPDATE_USERS: 'update-users',
        UPDATE_GROUP: 'update-group',
        UPDATE_PASSWORD: 'update-password',
        UPDATE_ROLE: 'update-role',
        DELETE_USERS: 'delete-users',
        DELETE_GROUPS: 'delete-groups',
        DELETE_ROLE: 'delete-role',
        DELETE_JOB: 'delete-job',
        PAUSE_JOB: 'pause-job',
        RESUME_JOB: 'resume-job',
        ASSIGN_USERS_TO_GROUPS: 'assign-users-to-groups',
        ASSIGN_PRINCIPALS_TO_ROLES: 'assign-principals-to-roles',
        ASSIGN_GROUPS_TO_GROUP: 'assign-groups-to-group',
        GET_SESSION_INFO: 'get-session-info',
        LOGIN: 'login',
        LOGOUT: 'logout',
        SAVE_CLIENT_STATE: 'save-client-state',
        FETCH_COMMENTS: 'fetch-comments',
        CREATE_COMMENT: 'create-comment',
        UPDATE_COMMENT: 'update-comment',
        DELETE_COMMENT: 'delete-comment',
        FETCH_DATA_SOURCE_TYPES: 'fetch-data-source-types',
        FETCH_DATA_SOURCE_SAMPLE_VALUES: 'fetch-data-source-sample-values',
        FETCH_COLUMN_STATISTICS: 'fetch-column-statistics',
        DELETE_DATA_SOURCE: 'delete-data-source',
        DATA_SOURCE_EXECUTE_DDL: 'data-source-execute-ddl',
        DATA_SOURCE_UPDATE_SCHEDULE: 'data-source-update-schedule',
        DATA_SOURCE_DELETE_SCHEDULE: 'data-source-delete-schedule',
        DATA_SOURCE_RELOAD_TASKS: 'data-source-reload-tasks',
        DATA_SOURCE_STOP_TASKS: 'data-source-stop-tasks',
        DATA_SOURCE_GET_CREATE_DDL: 'data-source-get-created-ddl',
        DATA_SOURCE_SCHEDULE_VALIDATION: 'data-source-schedule-validation',
        LOAD_FROM_DATA_SOURCE: 'load-from-data-source',
        EXPRESSION_VALIDATION: 'expression-validation',
        DATA_SOURCE_CREATE_CONNECTION: 'data-source-create-connection',
        DATA_SOURCE_DELETE_CONNECTION: 'data-source-delete-connection',
        DATA_SOURCE_EDIT_CONNECTION: 'data-source-edit-connection',
        CREATE_DATA_SOURCE: 'create-data-source',
        CONNECT_TO_DATA_SOURCE: 'connect-to-data-source',
        GET_DATA_SOURCE_CONN_FIELD_LIST: 'get-data-source-conn-field-list',
        GET_DATA_SOURCE_CONNECTION_LIST: 'get-data-source-connection-list',
        GET_DATA_SOURCE_CONNECTION_ATTRIBUTES: 'get-data-source-connection-attributes',
        GET_DATA_SOURCE_CONNECTIONS: 'get-data-source-connections',
        GET_DATA_SOURCE_CONFIG: 'get-data-source-config',
        FETCH_LOGIN_CONFIG: 'fetch-login-config',
        FETCH_SLACK_CONFIG: 'fetch-slack-config',
        HEALTH_CHECK: 'health-check',
        HELP_PORTAL_TOKEN: 'help-portal-token',
        HELP_PORTAL_RELEASE_NAME: 'help-portal-release-name',
        FETCH_PROFILE_PIC: 'fetch-profile-pic',
        UPLOAD_PROFILE_PIC: 'upload-profile-pic',
        UPLOAD_FILE: 'upload-file',
        UPGRADE_ANSWER: 'upgrade-answer',
        SEND_LOGS_TO_SERVER: 'send-logs-to-server',
        FETCH_RELATIONSHIP_DEPENDENTS: 'fetch-relationship-dependents',
        SAVE_RLS_RULE: 'save-rls-rule',
        DELETE_RLS_RULE: 'delete-rls-rule',
        REPORT_PROBLEM: 'report-problem',
        SHARE_OBJECT: 'share-object',
        SUBMIT_SAGE_FEEDBACK: 'submit-sage-feedback',
        REFRESH_CONTEXT_GUIDS: 'refresh-context-guids',

        // Cluster status service
        SEARCH_SUMMARY: 'search-summary',
        SEARCH_DETAIL_TABLE: 'search-detail-table',
        DATABASE_SUMMARY: 'database-summary',
        DATABASE_DETAIL: 'database-detail',
        CLUSTER_SUMMARY: 'cluster-stats-summary',
        CLUSTER_DETAIL_INFO: 'cluster-detail-info',
        CLUSTER_DETAIL_LOG: 'cluster-detail-log',
        CLUSTER_DETAIL_SNAPSHOT: 'cluster-detail-snapshot',
        ALERT_SUMMARY: 'alert-summary',
        EVENT_SUMMARY: 'event-summary',
        ALERTS_DETAILS_ALERTS: 'alerts-details-alerts',
        ALERTS_DETAILS_EVENTS: 'alerts-details-events',
        VALIDATE_TRANSFORMATION_EXPRESSION: 'validate-transformation-expression',
        DATASOURCE_CONN_OBJS_MISMATCH: 'datasource-conn-objs-mismatch',
        LOAD_SAVED_ANSWER: 'load-saved-answer',
        UPDATE_EXPOSED_PREFERENCES: 'update-exposed-preferences',
        UPDATE_CUSTOM_STYLE_CONFIG: 'update-custom-style-config'
    };

    /**
     * @param {userActionTypeEnum}  userActionType
     * @param {Object}              params
     * @param {Array.<String>}      params.messageParams
     */
    var UserAction = function(userActionType, params) {
        this.type = userActionType;
        if (!!params) {
            this.messageParams = params.messageParams;
        }
    };

    //TODO(Rahul): These properties can be moved to type field in UserAction
    Object.keys(userActionTypeEnum).forEach(function(key) {
        UserAction[key]= userActionTypeEnum[key];
    });

    return UserAction;
}]);
