//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

if (typeof thrift === 'undefined') {
  thrift = {};
}
if (typeof thrift.Sage === 'undefined') {
  thrift.Sage = {};
}
if (typeof thrift.Sage.AutoComplete === 'undefined') {
  thrift.Sage.AutoComplete = {};
}
